USE [master]
GO

/****** Object:  Database [QLBanHang]    Script Date: 1/11/2023 11:13:09 AM ******/
CREATE DATABASE [QLBanHang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLBanHang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\QLBanHang.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QLBanHang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\QLBanHang_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QLBanHang] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLBanHang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLBanHang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLBanHang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLBanHang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLBanHang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLBanHang] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLBanHang] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLBanHang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLBanHang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLBanHang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLBanHang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLBanHang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLBanHang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLBanHang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLBanHang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLBanHang] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLBanHang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLBanHang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLBanHang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLBanHang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLBanHang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLBanHang] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLBanHang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLBanHang] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLBanHang] SET  MULTI_USER 
GO

ALTER DATABASE [QLBanHang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLBanHang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLBanHang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLBanHang] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QLBanHang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLBanHang] SET  READ_WRITE 
GO

